config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index', as: :home
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/topics' => 'topics#index', as: :topics
  get '/topics/:id' => 'topics#show', as: :topic
  get '/subtopics' => 'subtopics#index'
  get '/subtopics/:id' => 'subtopics#show', as: :subtopic
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subtopic.rb
class Subtopic < ApplicationRecord
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :subtopics
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/subtopics_controller.rb
class SubtopicsController < ApplicationController
  def index
    @subtopics = Subtopic.all
  end

  def show
    @subtopic = Subtopic.find(params[:id])
    @topic = @subtopic.topic
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
    @subtopics = @topic.subtopics
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/subtopics_helper.rb
module SubtopicsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/subtopics/show.html.erb
<!DOCTYPE html>
<html>
<title>CSLearnTool</title>
<body>
<div class="page_wrap">
  <span class="sidebar"><h2>Contents</h2><br><%=link_to "Topics", topics_path %></span>
<div class="main">
  <div class="headings_bar">
    <h1><%= link_to "Trylobyte", welcome_index_path %></h1>
    <h2><%= link_to "Home", welcome_index_path %> >> <%= link_to "Topics", topics_path %> >> <%= link_to @topic.title, topic_path(@topic) %> >> <%= @subtopic.title %></h2>
  </div>
  <div class="content">
    <h3><%= @subtopic.title %></h3>
    <%= @subtopic.intro.html_safe %>
    <br>
    <div class="game_normal" <%= @subtopic.game_class.html_safe %>>
      <%= @subtopic.game.html_safe %>
    </div>
    <br>
    <%= @subtopic.main_content.html_safe %>
    <br>
    <h3>Try out the test!</h3>
    <iframe height="400" width="600" scrolling="no" src=<%= @subtopic.test %> ></iframe>
    <br>
    <h3>Summary</h3>
    <%= @subtopic.summary.html_safe %>
  </div>
</div>
</div>
</body>
</html>

app/views/topics/index.html.erb
<!DOCTYPE html>
<html>
<title>CSLearnTool</title>
<body>
<span class="sidebar"><h2>Contents</h2><br>
  <%=link_to "Topics", topics_path %></span>
<span class="main">
  <h1><%= link_to "Trylobyte", welcome_index_path %></h1>
  <h2><%= link_to "Home", welcome_index_path %> >> Topics</h2>
  <div class="content">
    Choose a topic.<br><br>
    <% @topics.each do |t| %>
      <%= link_to topic_path(t) do%>
        <div class="boxed_options">
          <%#= image_tag t.image %>
          <%= t.title %>
        </div>
      <% end %>
      <br>
    <% end %>
  </div>
</span>
</body>
</html>

app/views/topics/show.html.erb
<!DOCTYPE html>
<html>
<title>CSLearnTool</title>
<body>
<span class="sidebar"><h2>Contents</h2><br>
  <%=link_to "Topics", topics_path %></span>
<span class="main">
  <h1><%= link_to "Trylobyte", welcome_index_path %></h1>
  <h2><%= link_to "Home", welcome_index_path %> >> <%= link_to "Topics", topics_path %> >> <%= @topic.title %></h2>
  <div class="content">
    Choose a lesson.<br><br>
    <% @subtopics.each do |s| %>
      <%= link_to subtopic_path(s) do %>
      <div class="boxed_options">
        <%= s.title %>
      </div>
      <% end %>
      <br>
    <% end %>
  </div>
</span>
</body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<title>CSLearnTool</title>
<body>
<span class="sidebar"><h2>Contents</h2><br><%=link_to "Topics", topics_path %></span>
<span class="main">
  <h1>Trylobyte</h1>
  <h2>Home</h2>
  <div class="content">Welcome to Trylobyte!  Click on the topics button below to start looking for Computing topics to
    learn about.
    <br><br>
    <%= link_to topics_path do %>
      <div class="boxed_options">Topics</div>
    <% end %>
<!--    <div class="boxed_options">Badges</div>-->
  </div>
</span>
</body>
</html>